### PR TITLE
Feature/clear database

### PR DESCRIPTION
**Pull request by b2aguirr**
Fixed timeline UI.
Made a reset function which resets user points and re-assigns a new animal on a new day.

### CODE REVIEW

**Comment by hwanggit** [comment]
Hey Brian, should you be merging to Karl's branch or the develop branch?

**Comment by hwanggit** [comment]
Please resolve the merge conflicts before merging

**Comment by kwkarlwang** [comment]
> Hey @b2aguirr , should you be merging to Karl's branch or the develop branch?

Since I separated the files, I will be relocating Brian's functions to my branch first, then make sure there is no error. In the end, I will push these changes on develop branch

**Comment by trevdevv** [comment]
- These changes need to be merged into the develop branch. If you would like Karls latest changes on his branch you can perform a 'git pull origin tests/mock-tests-for-backend_Karl
I will close this pull request

**Comment by kwkarlwang** [comment]
The reset animal function has been move to userAndTeams.js, on a new day, everyone will be assign on a new animal.

**Pull request merged**
